### PR TITLE
Add ExchangeRate-API.com

### PR DESCRIPTION
**Pull request by longnull**

### CODE REVIEW

**Review by n0shake — CHANGES_REQUESTED** [review]
Can you link directly to the documentation page please?

**Comment by n0shake** [comment]
Looks like your branch has merge conflicts. Can you rebase on top of master and resolve any conflicts?

**Comment by longnull** [comment]
> This branch has no conflicts with the base branch

I didn't change anything 🙃

**Comment by n0shake** [comment]
@longnull Seeing this on my end :/ 

Screen Shot 2020-10-11 at 7 19 38 PM

**Comment by longnull** [comment]
I'll create a new PR 🙈

**Pull request closed without merging**
