### PR TITLE
Add Vector Express to File Storage and Manipulation

### PR DESCRIPTION
**Pull request by FrankSandqvist**

### CODE REVIEW

**Comment by n0shake** [comment]
Thanks @FrankSandqvist for the contribution. Can you fix the conflicts?

**Comment by FrankSandqvist** [comment]
> Thanks @FrankSandqvist for the contribution. Can you fix the conflicts?

Done 👍

**Comment by knslhacker** [comment]
Ok

**Comment by n0shake** [comment]
Screen Shot 2021-10-30 at 4 48 27 PM


There still seem to be conflicts! Please open a new PR and resubmit your changes.

**Pull request closed without merging**
