### PR TITLE
add LeetCode API

### PR DESCRIPTION
**Pull request by nkilm**
Please ensure your pull request adheres to the following guidelines:

- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Make an individual pull request for each suggestion.
- [x] Titles should be capitalized.
- [x] Keep descriptions short and simple.
- [x] End all descriptions with a full stop/period.
- [x] Check your spelling and grammar.
- [x] Make sure your text editor is set to remove trailing whitespace.
- [x] Try to make your Pull request and title as descriptive as possible.
- [x] Mark open source APIs with the open source icon
- [x] Mark all trial/demo based APIs with the 💸 emoticon.
- [x] Keep the APIs sorted alphabetically.
- [x] Whenever possible link directly to the documentation page!

## Examples

[Run in Postman](https://god.gw.postman.com/run-collection/18539765-867631d7-95f6-441f-b13a-3348d1a9b67b?action=collection%2Ffork&collection-url=entityId%3D18539765-867631d7-95f6-441f-b13a-3348d1a9b67b%26entityType%3Dcollection%26workspaceId%3D57f3520c-de94-464b-a9f0-7645a50f05f1)

- Get **Question of Today**
```http
POST https://leetcode.com/graphql HTTP/1.1
Content-Type: application/json

{
        "query":
          "\n    query questionOfToday {\n  activeDailyCodingChallengeQuestion {\n    date\n    userStatus\n    link\n    question {\n      acRate\n      difficulty\n      freqBar\n      frontendQuestionId: questionFrontendId\n      isFavor\n      paidOnly: isPaidOnly\n      status\n      title\n      titleSlug\n      hasVideoSolution\n      hasSolution\n      topicTags {\n        name\n        id\n        slug\n      }\n    }\n  }\n}\n    "
} 
```
- **Site Announcements** - returns `null` if not site announcements
```http
POST https://leetcode.com/graphql HTTP/1.1
Content-Type: application/json

{
        "query":
          "\n    query siteAnnouncements {\n  siteAnnouncements {\n    title\n    content\n    blacklistUrls\n    whitelistUrls\n    navbarItem\n  }\n}\n    "
} 
```

- Fetch all **submissions of a user** with given username.

```http
POST https://leetcode.com/graphql HTTP/1.1
Content-Type: application/json

{
        "query":
          "\n    query userProblemsSolved($username: String!) {\n  matchedUser(username: $username) {\n    submitStatsGlobal {\n      acSubmissionNum {\n        difficulty\n        count\n      }\n    }\n  }\n}\n    ",
        "variables": { "username": "neal_wu" }
} 
```

- Ongoing virtual contest
```http
POST https://leetcode.com/graphql HTTP/1.1
Content-Type: application/json

{
        "query":
          "\n    query ongoingVirtualContest {\n  ongoingVirtualContest {\n    titleSlug\n  }\n}\n    "

} 
```

**Note: Unfortunately, there is currently no documentation available for the API. However, you can obtain desired query by inspecting the network section of a web browser.**

### CODE REVIEW

**Review by CaedenPH — CHANGES_REQUESTED** [review]
Personally I don't think that this should be on the list, because it is related to specific user accounts on a platform. If this is implemented then any site that returns user info (such as the github graphql endpoint) should be on here as well. If the leetcode api returned coding problems or challenges, I would be all for it but as it is specific to user accounts and its primary function is for if you have a leetcode account and want to grab data, I dislike this endpoint being on this list

**Comment by nkilm** [comment]
@CaedenPH 

> Personally I don't think that this should be on the list, because it is related to specific user accounts on a platform. If this is implemented then any site that returns user info (such as the github graphql endpoint) should be on here as well. If the leetcode api returned coding problems or challenges, I would be all for it but as it is specific to user accounts and its primary function is for if you have a leetcode account and want to grab data, I dislike this endpoint being on this list

I completely understand your point, and it's valid to say that the Leetcode API is specific to user accounts on a particular platform. However, I'd like to add that the API can provide much more than just user details. It can also fetch problems and challenges based on different criteria, which might be helpful in creating a dataset for analysis. While it's true that other APIs like the Github GraphQL endpoint can return user info, it doesn't necessarily mean we shouldn't consider adding the Leetcode API to the public APIs list.

Here is another example query to retrieve the **problem of the day**

image

**Comment by CaedenPH** [comment]
@nkilm I wasn't aware that it returned other data - In that case, I think that it should be considered, but perhaps you could add that it returns also problems to the pr description.

**Comment by nkilm** [comment]
@CaedenPH Please check, I've added additional examples as you've requested.

**Review by CaedenPH — APPROVED** [review]
Thanks, seems like a more useful endpoint now!

**Comment by n0shake** [comment]
@nkilm thanks for the PR! https://leetcode.com/graphql is right now returning:

> {"errors":[{"message":"Must provide query string."}]}

Can you link to the documentation page directly please?

**Review by n0shake — CHANGES_REQUESTED** [review]
Let's link to the doc pls.

**Comment by nkilm** [comment]
> @nkilm thanks for the PR! [leetcode.com/graphql](https://leetcode.com/graphql) is right now returning:
> 
> > {"errors":[{"message":"Must provide query string."}]}
> 
> Can you link to the documentation page directly please?

This error is returned by the API when we don't provide the query. This is [graphql API](https://graphql.org/), so it is mandatory to provide queries inorder to fetch desired information. 

As of now, there is no official documentation for the LeetCode API. But we can get the queries for the API by analyzing the network tab of the website(I've given an example above). This should be sufficient for most of the cases.

Example using [curl](https://curl.se/)
```bash
curl -X POST https://leetcode.com/graphql -H "Content-Type: application/json" --data '{"query":"\n    query questionOfToday {\n  activeDailyCodingChallengeQuestion {\n    date\n    userStatus\n    link\n    question {\n      acRate\n      difficulty\n      freqBar\n      frontendQuestionId: questionFrontendId\n      isFavor\n      paidOnly: isPaidOnly\n      status\n      title\n      titleSlug\n      hasVideoSolution\n      hasSolution\n      topicTags {\n        name\n        id\n        slug\n      }\n    }\n  }\n}\n    "}'
```

**Pull request closed without merging**
