### PR TITLE
Added TikTok API and removed duplicate entry of Breakin Bad Quotes API from misc section

### LINKED ISSUE #532: Breaking bad quotes is mentioned two times. One under quotes section and the other one in misc section
## In Miscellaneous section
brba2

## In Quotes Section
brba1

Breaking bad and better call saul api has been already listed in **Entertainment** section which gives data about apisodes, castsm, plot and quotes. But the above mentioned api is a limited quotes api. Since it is about quotes, it can be removed from **Miscellaneous** section perhaps.
Thank you

### PR DESCRIPTION
**Pull request by yunghog**
Please ensure your pull request adheres to the following guidelines:

- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Make an individual pull request for each suggestion.
- [x] Titles should be capitalized.
- [x] Keep descriptions short and simple.
- [x] End all descriptions with a full stop/period.
- [x] Check your spelling and grammar.
- [x] Make sure your text editor is set to remove trailing whitespace.
- [x] Try to make your Pull request and title as descriptive as possible.
- [x] Mark open source APIs with the open source icon
- [x] Mark all trial/demo based APIs with the 💸 emoticon.
- [x] Keep the APIs sorted alphabetically.
- [x] Whenever possible link directly to the documentation page!

fixes #532

### CODE REVIEW

**Comment by n0shake** [comment]
Is the TikTok API open-source?

**Comment by yunghog** [comment]
> Is the TikTok API open-source?

Yes I guess. No need to add credit card or any kind of pricing

**Comment by n0shake** [comment]
We add the open-source icon when the code is available to the general public; can you link the TikTok code repository? @yunghog

**Comment by yunghog** [comment]
> We add the open-source icon when the code is available to the general public; can you link the TikTok code repository? @yunghog

Ok let me change it real quick. Thanks for the info

**Review by n0shake — APPROVED** [review]

**Comment by n0shake** [comment]
thank you @yunghog  :)

**Pull request merged**
