### PR TITLE
Dynamic QR Code added

### PR DESCRIPTION
**Pull request by Paulo-2048**
This API is focused on generating dynamic (content can be changed later) and static QR Codes, with constant updates. With it, you’ll never have to worry about creating a QR code again for your application - use our API to generate your QR codes  just a few lines of code.

- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] Make an individual pull request for each suggestion.
- [x] Titles should be capitalized.
- [x] Keep descriptions short and simple.
- [x] End all descriptions with a full stop/period.
- [x] Check your spelling and grammar.
- [x] Make sure your text editor is set to remove trailing whitespace.
- [x] Try to make your Pull request and title as descriptive as possible.
- [x] Mark open source APIs with the open source icon
- [x] Mark all trial/demo based APIs with the 💸 emoticon.
- [x] Keep the APIs sorted alphabetically.
- [x] Whenever possible link directly to the documentation page!

### CODE REVIEW

**Comment by n0shake** [comment]
The page mentions it's under construction; is the API ready?

Screen Shot 2022-08-03 at 4 29 49 PM

**Comment by Paulo-2048** [comment]
@n0shake 

Yes, the API itself is ready, it's just under construction some points related to documentation, and presentation of use cases for example.

But the API itself is fully functional.

**Comment by Paulo-2048** [comment]
@n0shake 

Yes, the API itself is ready, it's just under construction some points related to documentation, and presentation of use cases for example.

But the API itself is fully functional.

**Comment by n0shake** [comment]
Can you link to the Endpoints page or some other documentation, please? The URL makes it seem like it's broken.

**Comment by Paulo-2048** [comment]
Right @n0shake, I'll see if I can create a documentation with swagger or something similar, once I've done it I'll make a new comment here tagging you.

**Comment by Paulo-2048** [comment]
Right @n0shake, I'll see if I can create a documentation with swagger or something similar, once I've done it I'll make a new comment here tagging you.

**Comment by n0shake** [comment]
Please open a new PR when that happens :)

**Pull request closed without merging**
